[package]
name = "fetcher"
version = "0.0.1"
license = "MIT"
authors = ["David Barnett <david@barnett.net.nz>"]

[features]
unstable = []

[lib]
name = "fetcher"
path = "src/lib.rs"

[[bin]]
name = "fetchd"
path = "src/main.rs"

[dependencies]
hyper = "*"
url = "*"
rustc-serialize = "*"
sxd-xpath = "*"
sxd-document = "*"
# log = "*"
# env_logger = "*"
